on:
  workflow_dispatch: {} # Allow manually kicking off builds
  schedule:
    - cron:  '0 12 * * *' # Every day at 12:00 (noon). Ref https://crontab.guru/examples.html
name: Scrape telegram bot API
jobs:
  build:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: >
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Scrape website
      run: python scrape.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
        commit_message: Regenerate bot API docs.
        # Optional commit user and author settings
        commit_user_name: Yasir Aris M # defaults to "github-actions[bot]"
        commit_user_email: yasiramunandar@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
        commit_author: Yasir <yasiramunandar@gmail.com> # defaults to author of the commit that triggered the run
